### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by josefnpat** [kyle-emmerich/nox-astra#1]
It doesn't run! :cry: 

    seppi@seppi7:~/repos/nox-astra♠ love .
    Segmentation fault (core dumped)

**Comment by kyle-emmerich** [comment]
Sorry, can't help you there

**Comment by kyle-emmerich** [comment]
So let's rule out LPGhatguy's guilt by removing everything but Carbon and seeing if it works for you at all.

1. Remove everything but the Carbon folder, graphene.lua, and main.lua.
2. Remove everything in main.lua except for lines 1 and 2.
3. Add a new file called Test.clua in the folder (yes, clua, not lua!)
4. In Test.clua, print something, like print("buttbeef")
5. Go back to main.lua, add the following:
    local test = Core.Test
6. Run it.

**Comment by josefnpat** [comment]
seppi@seppi7:~/repos/nox-astra♠ git status
    On branch master
    Your branch is up-to-date with 'origin/master'.
    Changes not staged for commit:
      (use "git add/rm <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)

	    deleted:    Assets/Fonts/Khula-Bold.ttf
	    deleted:    Assets/Fonts/Khula-ExtraBold.ttf
	    deleted:    Assets/Fonts/Khula-Light.ttf
	    deleted:    Assets/Fonts/Khula-Regular.ttf
	    deleted:    Assets/Fonts/Khula-SemiBold.ttf
	    deleted:    Assets/Fonts/OFL.txt
	    deleted:    Assets/Ships/Centauri/data.nsd
	    deleted:    Assets/Ships/Centauri/hull.png
	    deleted:    Graphics/Sprite.clua
	    deleted:    README.md
	    deleted:    State.clua
	    deleted:    StateMachine.clua
	    deleted:    States/MainMenu.clua
	    deleted:    System.lua
	    deleted:    Utility/LoadHelpers.lua
	    deleted:    Utility/polyfill.lua
	    deleted:    conf.lua
	    modified:   main.lua
	    deleted:    project.sublime-project

    Untracked files:
      (use "git add <file>..." to include in what will be committed)

	    Test.clua

    no changes added to commit (use "git add" and/or "git commit -a")
    seppi@seppi7:~/repos/nox-astra♠ cat Test.clua 
    print("buttbeef")
    seppi@seppi7:~/repos/nox-astra♠ git diff main.lua 
    diff --git a/main.lua b/main.lua
    index 39eaf47..9b25d6e 100644
    --- a/main.lua
    +++ b/main.lua
    @@ -1,7 +1,4 @@
     local Core = require("graphene")
     Core:AddGrapheneSubmodule("Carbon")
     
    -require('Utility.polyfill')
    -
    -local System = Core.System
    -System:SetState(Core.States.MainMenu)
    \ No newline at end of file
    +local test = Core.Test
    seppi@seppi7:~/repos/nox-astra♠ love .
    Segmentation fault (core dumped)

@LPGhatguy - I assume I should open this as a ticket on Carbon. If I knew where the repo was.

**Comment by LPGhatguy** [comment]
There's nothing that should be issuing a segfault in Carbon, I don't create any sort of cdata or do anything unsafe by default.

**Comment by kyle-emmerich** [comment]
Since this is a Carbon issue and will be fixed there, I'll close this issue!
